apiVersion: apps/v1
kind: Deployment
metadata:
  name: proof-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proof-api
  template:
    metadata:
      labels:
        app: proof-api
    spec:
      containers:
      - name: proof-api
        image: proof/api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: proof-api-config
